### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by WalonDreamer** [qiuhoude/AMapClusterLib#1]
Error:Execution failed for task ':sample:transformResourcesWithMergeJavaResForDebug'.

> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK assets/ap1.data
>     File1: G:\amap\AMapClusterLib-master\sample\libs\AMap_3DMap_V3.3.2_20160525.jar
>     File2: G:\amap\AMapClusterLib-master\sample\build\intermediates\exploded-aar\AMapClusterLib-master\amapclusterlib\unspecified\jars\classes.jar

**Comment by qiuhoude** [comment]
好像是 高德的包重复导入的问题,你删掉sample下的AMap_3DMap_V3.3.2_20160525.jar试试
